# Generated by Django 2.2.19 on 2025-09-04 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arquitectura', '0056_campaña_cotizacion_cultivo_establecimiento_zona_zonasporcultivo'),
        ('consorcios', '0009_auto_20250811_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estatuto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('numero', models.CharField(blank=True, max_length=50, null=True)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('consorcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consorcios.Consorcio')),
            ],
            options={
                'ordering': ['-fecha', 'nombre'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConvenioDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('numero', models.CharField(blank=True, max_length=50, null=True)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('consorcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consorcios.Consorcio')),
            ],
            options={
                'ordering': ['-fecha', 'nombre'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActaJuntaFiscalizadora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('numero', models.CharField(blank=True, max_length=50, null=True)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('consorcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consorcios.Consorcio')),
                ('integrantes', models.ManyToManyField(blank=True, to='arquitectura.Socio')),
            ],
            options={
                'verbose_name': 'Acta de Junta Fiscalizadora',
                'verbose_name_plural': 'Actas de Junta Fiscalizadora',
                'ordering': ['-fecha', 'nombre'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActaConsejo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('numero', models.CharField(blank=True, max_length=50, null=True)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('consorcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consorcios.Consorcio')),
                ('integrantes', models.ManyToManyField(blank=True, to='arquitectura.Socio')),
            ],
            options={
                'verbose_name': 'Acta de Consejo',
                'verbose_name_plural': 'Actas de Consejo',
                'ordering': ['-fecha', 'nombre'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActaAsamblea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('numero', models.CharField(blank=True, max_length=50, null=True)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('consorcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consorcios.Consorcio')),
                ('integrantes', models.ManyToManyField(blank=True, to='arquitectura.Socio')),
            ],
            options={
                'verbose_name': 'Acta de Asamblea',
                'verbose_name_plural': 'Actas de Asamblea',
                'ordering': ['-fecha', 'nombre'],
                'abstract': False,
            },
        ),
    ]
