# Generated by Django 2.2.19 on 2025-09-08 20:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actaasamblea',
            name='contenido',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(50000)]),
        ),
        migrations.AlterField(
            model_name='actaconsejo',
            name='contenido',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(50000)]),
        ),
        migrations.AlterField(
            model_name='actajuntafiscalizadora',
            name='contenido',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(50000)]),
        ),
        migrations.AlterField(
            model_name='conveniodoc',
            name='contenido',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(200000)]),
        ),
        migrations.AlterField(
            model_name='estatuto',
            name='contenido',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(2000000)]),
        ),
    ]
