# Generated by Django 2.2.19 on 2025-09-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0002_auto_20250908_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='actaasamblea',
            name='firma',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actaasamblea',
            name='foja',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actaasamblea',
            name='transcripcion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actaconsejo',
            name='firma',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actaconsejo',
            name='foja',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actaconsejo',
            name='transcripcion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actajuntafiscalizadora',
            name='firma',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actajuntafiscalizadora',
            name='foja',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actajuntafiscalizadora',
            name='transcripcion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conveniodoc',
            name='firma',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conveniodoc',
            name='transcripcion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estatuto',
            name='firma',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estatuto',
            name='transcripcion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='actaasamblea',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actaconsejo',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actajuntafiscalizadora',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conveniodoc',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estatuto',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
