# Generated by Django 2.2.19 on 2023-12-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensas_pagas', '0003_documentoexp'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobroexp',
            name='ingreso',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
