# Generated by Django 2.2.19 on 2023-12-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensas_pagas', '0004_cobroexp_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobroexp',
            name='ingreso',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
