# Generated by Django 2.2.19 on 2025-09-26 22:37

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arquitectura', '0056_campaña_cotizacion_cultivo_establecimiento_zona_zonasporcultivo'),
        ('consorcios', '0009_auto_20250811_1812'),
        ('afip', '0006_auto_20250926_1825'),
        ('creditos', '0007_auto_20190102_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaUSD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('cotizacion', models.DecimalField(decimal_places=4, help_text='Tipo de cambio aplicado (ARS/USD)', max_digits=12)),
                ('total_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('consorcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consorcios.Consorcio')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='afip.Receipt')),
                ('socio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='arquitectura.Socio')),
            ],
            options={
                'verbose_name': 'Factura en USD',
                'verbose_name_plural': 'Facturas en USD',
            },
        ),
        migrations.CreateModel(
            name='CreditoUSD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('periodo', models.DateField(blank=True, null=True)),
                ('capital_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('detalle', models.CharField(blank=True, max_length=100, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
                ('cotizacion', models.DecimalField(blank=True, decimal_places=4, help_text='Tipo de cambio (ARS/USD) vigente para este crédito', max_digits=12, null=True)),
                ('consorcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consorcios.Consorcio')),
                ('factura_usd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creditos_usd', to='creditos.FacturaUSD')),
                ('ingreso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arquitectura.Ingreso')),
                ('socio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arquitectura.Socio')),
            ],
            options={
                'verbose_name': 'Crédito en USD',
                'verbose_name_plural': 'Créditos en USD',
            },
        ),
    ]
