# Generated by Django 2.2.19 on 2025-09-26 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0008_creditousd_facturausd'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoUSD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='facturausd',
            name='punto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creditos.PuntoUSD'),
        ),
    ]
