# Generated by Django 2.2.19 on 2025-09-29 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consorcios', '0009_auto_20250811_1812'),
        ('creditos', '0009_auto_20250926_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntousd',
            name='consorcio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consorcios.Consorcio'),
        ),
    ]
