# Generated by Django 2.2.19 on 2025-08-11 21:06

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arquitectura', '0056_campaña_cotizacion_cultivo_establecimiento_zona_zonasporcultivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('suscripcion', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Suscripcion')),
                ('campaña', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arquitectura.Campaña')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arquitectura.Socio')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudLinea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participacion', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Participacion')),
                ('hectarea', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Hectareas')),
                ('subsidio_max', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Subsidio max QQ')),
                ('aporte_max', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='% Aporte max')),
                ('aporte_total_qq', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Aporte total QQ')),
                ('cultivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arquitectura.Cultivo')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arquitectura.Establecimiento')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='fosea.Solicitud')),
            ],
        ),
    ]
