# Generated by Django 2.2.19 on 2025-08-13 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consorcios', '0009_auto_20250811_1812'),
        ('fosea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='consorcio',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='consorcios.Consorcio'),
            preserve_default=False,
        ),
    ]
