# Generated by Django 2.2.19 on 2025-08-20 12:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fosea', '0002_solicitud_consorcio'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudlinea',
            name='franquicia',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Franquicia'),
        ),
    ]
