# Generated by Django 2.2.19 on 2025-10-29 22:52

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consorcios', '0009_auto_20250811_1812'),
        ('arquitectura', '0057_ingreso_cuenta_activo'),
        ('fosea', '0003_solicitudlinea_franquicia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siniestro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('indemnizacion_total_qq', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('indemnizacion_total_ars', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('campaña', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arquitectura.Campaña')),
                ('consorcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consorcios.Consorcio')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arquitectura.Socio')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SiniestroLinea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hectareas_afectadas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('danio_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Daño (%)')),
                ('franquicia_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Franquicia (%)')),
                ('cobertura_qq', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Cobertura (QQ/ha)')),
                ('estadio', models.CharField(blank=True, max_length=32, null=True)),
                ('liberacion', models.CharField(choices=[('plena', 'Cobertura plena (100%)'), ('resiembra_etapa', 'Etapa resiembra (40%)'), ('liberacion_lote', 'Liberación de lote (80%)'), ('resiembra_efectiva', 'Resiembra efectiva (20%)')], default='plena', max_length=32)),
                ('indemnizacion_qq', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('indemnizacion_ars', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arquitectura.Cultivo')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arquitectura.Establecimiento')),
                ('siniestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='fosea.Siniestro')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
