# Generated by Django 2.2.19 on 2025-11-06 19:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fosea', '0004_siniestro_siniestrolinea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siniestro',
            name='indemnizacion_total_ars',
        ),
        migrations.RemoveField(
            model_name='siniestrolinea',
            name='indemnizacion_ars',
        ),
        migrations.AddField(
            model_name='siniestro',
            name='indemnizacion_total_ajustada',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='siniestrolinea',
            name='indemnizacion_ajustada',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
    ]
