# Generated by Django 2.2.19 on 2023-11-29 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consorcios', '0004_consorcio_proveeduria'),
    ]

    operations = [
        migrations.AddField(
            model_name='consorcio',
            name='matricula',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
