# Generated by Django 2.2.19 on 2024-03-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consorcios', '0005_consorcio_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='consorcio',
            name='es_federacion',
            field=models.BooleanField(default=False),
        ),
    ]
