# Generated by Django 2.2.19 on 2024-06-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consorcios', '0007_auto_20240524_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='consorcio',
            name='convenios',
            field=models.BooleanField(default=False),
        ),
    ]
