# Generated by Django 2.2.19 on 2025-08-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consorcios', '0008_consorcio_convenios'),
    ]

    operations = [
        migrations.AddField(
            model_name='consorcio',
            name='chatia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consorcio',
            name='fosea',
            field=models.BooleanField(default=False),
        ),
    ]
