# Generated by Django 2.2.19 on 2024-01-15 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consorcios', '0005_consorcio_matricula'),
        ('proveeduria', '0004_transporte'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Depositos',
            new_name='Deposito',
        ),
    ]
