# Generated by Django 2.2.19 on 2024-01-24 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consorcios', '0005_consorcio_matricula'),
        ('proveeduria', '0006_comp_venta_consol_carga_guia_distri_informe_notas_pedido_recibo_provee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notas_pedido',
            new_name='NotasPedido',
        ),
    ]
