# Generated by Django 2.2.19 on 2025-08-07 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arquitectura', '0053_auto_20250807_0822'),
        ('proveeduria', '0008_auto_20240124_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='direccion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='lista_precio',
            field=models.CharField(choices=[('1', 'Lista de precios 1'), ('2', 'Lista de precios 2'), ('3', 'Lista de precios 3'), ('4', 'Lista de precios 4')], default='1', max_length=15),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='localidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='mail',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='provincia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='socio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arquitectura.Socio'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='nombre',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
