# Generated by Django 2.2.19 on 2025-08-07 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0007_auto_20190102_1146'),
        ('proveeduria', '0012_vendendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='comp_venta',
            name='deposito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proveeduria.Deposito'),
        ),
        migrations.AddField(
            model_name='comp_venta',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creditos.Factura'),
        ),
        migrations.AddField(
            model_name='comp_venta',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comp_venta',
            name='liquidacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creditos.Liquidacion'),
        ),
        migrations.AddField(
            model_name='comp_venta',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proveeduria.Sucursal'),
        ),
        migrations.AddField(
            model_name='comp_venta',
            name='transporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proveeduria.Transporte'),
        ),
        migrations.AddField(
            model_name='comp_venta',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proveeduria.Vendendor'),
        ),
    ]
