# Generated by Django 2.2.19 on 2025-08-07 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0007_auto_20190102_1146'),
        ('consorcios', '0008_consorcio_convenios'),
        ('proveeduria', '0013_auto_20250807_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta_Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('consorcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consorcios.Consorcio')),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creditos.Credito')),
                ('liquidacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creditos.Liquidacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveeduria.Producto')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveeduria.Sucursal')),
            ],
        ),
    ]
