# Generated by Django 2.2.19 on 2025-08-07 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consorcios', '0008_consorcio_convenios'),
        ('proveeduria', '0014_venta_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra_Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('consorcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consorcios.Consorcio')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveeduria.Producto')),
            ],
        ),
    ]
