# Generated by Django 2.2.19 on 2025-08-07 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveeduria', '0015_compra_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=9)),
                ('compra_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveeduria.Compra_Producto')),
                ('deposito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proveeduria.Deposito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveeduria.Producto')),
                ('venta_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveeduria.Venta_Producto')),
            ],
        ),
    ]
