# Generated by Django 2.2.19 on 2025-08-07 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arquitectura', '0055_caja_convenio'),
        ('proveeduria', '0017_auto_20250807_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='comp_venta',
            name='socio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arquitectura.Socio'),
        ),
        migrations.AddField(
            model_name='venta_producto',
            name='socio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arquitectura.Socio'),
        ),
        migrations.AlterField(
            model_name='venta_producto',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proveeduria.Sucursal'),
        ),
    ]
