# Generated by Django 2.2.19 on 2025-09-03 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveeduria', '0020_auto_20250829_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta_producto',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
