# Generated by Django 2.2.19 on 2025-09-19 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consorcios', '0009_auto_20250811_1812'),
        ('arquitectura', '0056_campaña_cotizacion_cultivo_establecimiento_zona_zonasporcultivo'),
        ('proveeduria', '0021_venta_producto_costo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('observacion', models.TextField(blank=True, null=True)),
                ('numero', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('consorcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consorcios.Consorcio')),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proveeduria.Deposito')),
                ('socio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arquitectura.Socio')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveeduria.Sucursal')),
                ('transporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveeduria.Transporte')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveeduria.Vendendor')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RemitoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=9)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('detalle', models.CharField(blank=True, max_length=200, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proveeduria.Producto')),
                ('remito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='proveeduria.Remito')),
            ],
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='remito_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveeduria.RemitoItem'),
        ),
    ]
