# Generated by Django 2.2.19 on 2025-09-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveeduria', '0022_auto_20250919_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='remitoitem',
            name='anulado',
            field=models.BooleanField(default=False),
        ),
    ]
