# Generated by Django 2.2.19 on 2025-09-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveeduria', '0023_remitoitem_anulado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remitoitem',
            name='anulado',
        ),
        migrations.AddField(
            model_name='remito',
            name='anulado',
            field=models.BooleanField(default=False),
        ),
    ]
