# Generated by Django 2.2.19 on 2025-09-24 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consorcios', '0009_auto_20250811_1812'),
        ('proveeduria', '0024_auto_20250922_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('motivo', models.TextField(blank=True, null=True)),
                ('anulado', models.BooleanField(default=False)),
                ('numero', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('consorcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consorcios.Consorcio')),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proveeduria.Deposito')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AjusteStockItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentido', models.CharField(choices=[('E', 'Entrada'), ('S', 'Salida')], max_length=1)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=9)),
                ('detalle', models.CharField(blank=True, max_length=200, null=True)),
                ('ajuste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='proveeduria.AjusteStock')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proveeduria.Producto')),
            ],
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='ajuste_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveeduria.AjusteStockItem'),
        ),
    ]
