# Generated by Django 2.2.19 on 2025-09-24 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveeduria', '0025_auto_20250924_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta_producto',
            name='es_nc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venta_producto',
            name='motivo_nc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='venta_producto',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones', to='proveeduria.Venta_Producto'),
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
