# Generated by Django 2.2.19 on 2025-10-01 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0011_auto_20181126_1659'),
        ('proveeduria', '0026_auto_20250924_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta_producto',
            name='comprobante_nc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vpc_nc', to='comprobantes.Comprobante'),
        ),
    ]
