# Generated by Django 2.2.19 on 2025-10-01 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveeduria', '0027_venta_producto_comprobante_nc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta_producto',
            name='comprobante_nc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vps_nc', to='comprobantes.Comprobante'),
        ),
    ]
