# Generated by Django 2.2.19 on 2025-10-08 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('op', '0004_notacreditolineagasto_notacreditolineaproducto_notacreditoproveedor'),
        ('proveeduria', '0028_auto_20251001_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra_producto',
            name='deuda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='op.Deuda'),
        ),
    ]
