# Generated by Django 2.2.19 on 2025-10-23 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveeduria', '0029_compra_producto_deuda'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_modulo',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ModuloComponente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proveeduria.Producto')),
                ('producto_modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='proveeduria.Producto')),
            ],
            options={
                'unique_together': {('producto_modulo', 'componente')},
            },
        ),
    ]
