# Generated by Django 2.2.19 on 2023-11-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquitectura', '0040_auto_20231107_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='es_cuotasocial',
            field=models.BooleanField(default=False),
        ),
    ]
