# Generated by Django 2.2.19 on 2023-11-22 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arquitectura', '0041_ingreso_es_cuotasocial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingreso',
            old_name='es_cuotasocial',
            new_name='es_cuota_social',
        ),
    ]
