# Generated by Django 2.2.19 on 2024-03-14 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquitectura', '0043_auto_20240202_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='cant_socios',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='gerente',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='presidente',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='secretario',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='tesorero',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
