# Generated by Django 2.2.19 on 2024-03-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquitectura', '0044_auto_20240314_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='activos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='adherentes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='honorarios',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='participantes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
