# Generated by Django 2.2.19 on 2024-03-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquitectura', '0045_auto_20240314_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='es_proveeduria',
            field=models.BooleanField(default=False),
        ),
    ]
