# Generated by Django 2.2.19 on 2024-04-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquitectura', '0046_ingreso_es_proveeduria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='nombre',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
