# Generated by Django 2.2.19 on 2024-06-13 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consorcios', '0007_auto_20240524_1952'),
        ('arquitectura', '0049_auto_20240524_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(max_length=10000, null=True)),
                ('reglamento', models.TextField(max_length=10000, null=True)),
                ('baja', models.DateField(blank=True, null=True)),
                ('consorcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convenio', to='consorcios.Consorcio')),
            ],
        ),
    ]
