# Generated by Django 2.2.19 on 2025-08-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquitectura', '0053_auto_20250807_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='es_proveeduria',
            field=models.BooleanField(default=False),
        ),
    ]
