# Generated by Django 2.2.19 on 2025-08-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquitectura', '0054_gasto_es_proveeduria'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='convenio',
            field=models.BooleanField(default=False),
        ),
    ]
