# Generated by Django 2.2.19 on 2025-08-11 21:06

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consorcios', '0008_consorcio_convenios'),
        ('arquitectura', '0055_caja_convenio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('consorcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consorcios.Consorcio')),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('consorcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consorcios.Consorcio')),
            ],
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('dpto', models.CharField(max_length=100, verbose_name='Departamento')),
                ('gps', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación GPS')),
                ('consorcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consorcios.Consorcio')),
                ('socio', models.ManyToManyField(related_name='establecimientos', to='arquitectura.Socio')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arquitectura.Zona')),
            ],
            options={
                'verbose_name': 'Establecimiento',
                'verbose_name_plural': 'Establecimientos',
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('cotizacion', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Cotización')),
                ('precio_flete', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Precio Flete')),
                ('comision', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Comisión (%)')),
                ('consorcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consorcios.Consorcio')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arquitectura.Cultivo')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Campaña',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('consorcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consorcios.Consorcio')),
            ],
        ),
        migrations.CreateModel(
            name='ZonasPorCultivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aporte_sin_siniestro', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Aporte sin siniestro (%)')),
                ('aporte_con_siniestro', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Aporte con siniestro (%)')),
                ('franquicia', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Franquicia (%)')),
                ('subsidio_maximo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Subsidio máximo')),
                ('consorcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consorcios.Consorcio')),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arquitectura.Cultivo')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arquitectura.Zona')),
            ],
            options={
                'verbose_name': 'Zona por Cultivo',
                'verbose_name_plural': 'Zonas por Cultivo',
                'unique_together': {('zona', 'cultivo')},
            },
        ),
    ]
