# Generated by Django 2.2.19 on 2025-10-09 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
        ('arquitectura', '0056_campaña_cotizacion_cultivo_establecimiento_zona_zonasporcultivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='cuenta_activo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingreso_activo', to='contabilidad.Cuenta'),
        ),
    ]
