# Generated by Django 2.2.19 on 2025-11-06 19:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquitectura', '0057_ingreso_cuenta_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaña',
            name='ajuste',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Ajuste (%)'),
        ),
    ]
