# Generated by Django 2.2.19 on 2025-10-08 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveeduria', '0028_auto_20251001_0901'),
        ('consorcios', '0009_auto_20250811_1812'),
        ('arquitectura', '0056_campaña_cotizacion_cultivo_establecimiento_zona_zonasporcultivo'),
        ('op', '0003_op_fecha_operacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaCreditoProveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('observacion', models.TextField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('es_proveeduria', models.BooleanField(default=False)),
                ('acreedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arquitectura.Acreedor')),
                ('consorcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consorcios.Consorcio')),
                ('deposito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveeduria.Deposito')),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_credito', to='op.Deuda')),
            ],
        ),
        migrations.CreateModel(
            name='NotaCreditoLineaProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas_productos', to='op.NotaCreditoProveedor')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveeduria.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='NotaCreditoLineaGasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arquitectura.Gasto')),
                ('nc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas_gastos', to='op.NotaCreditoProveedor')),
            ],
        ),
    ]
