# Generated by Django 2.2.19 on 2025-10-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op', '0004_notacreditolineagasto_notacreditolineaproducto_notacreditoproveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='notacreditoproveedor',
            name='total_aplicado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
