# Generated by Django 2.2.19 on 2025-10-14 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
        ('op', '0005_notacreditoproveedor_total_aplicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='notacreditoproveedor',
            name='asiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_credito_proveedor', to='contabilidad.Asiento'),
        ),
    ]
